name: BumpProviders

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup GIT token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout branch
        run: |
          git checkout -b bump-providers
  
      - name: Build
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: ./build.ps1

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Bump Providers
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            Invoke-Build ExportProviders
            $changedFiles = git diff --name-only
            if ($changedFiles -eq 'data/providers.json') {
              git add data/providers.json
              git commit -m 'Updated providers'
              git push origin bump-providers
              gh pr create --base 'main' --head 'bump-providers' --title 'Bump Providers data'
            }
            else {
              Write-Host 'Providers data up to date!'
            }
          azPSVersion: latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}